@echo off
echo Stopping any running Java processes...
taskkill /f /im java.exe >nul 2>&1
taskkill /f /im javaw.exe >nul 2>&1
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting fresh application...
ant clean compile && ant run
